name: PR creation
on:
  issues:
    types: ['opened']
      
jobs:
  test:
    if: github.event_name != 'push' && github.event_name != 'pull_request' && github.event_name != 'issue_comment' || contains(github.event.comment.body, '/validate') && (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Body
        uses: peter-murray/issue-body-parser-action@v1
        id: issue_body_parser
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    # This is assuming that you are triggering off the issue, otherwise you will need to know the issue number
          issue_id: ${{ github.event.issue.number }}
          payload: yaml
    
    
 
